### ISSUE TITLE
Azure SAS token results attempts invalid list operation container named 'name'

### ISSUE THREAD

**Issue by stewartadam** [Accelize/pycosio#23]
Here's a simple repro that attempts to download a URI:
```
import pycosio
import sys
from urllib.parse import urlparse

url = sys.argv[1]
components = urlparse(url)
parameters = {
    'account_name': account_name,
    'endpoint_suffix': endpoint_suffix,
    'sas_token': components.query
}
pycosio.mount(storage='azure_blob', storage_parameters=parameters)

# remove query string from blob_url, pycosio will think it's part of the filename
blob_url = urljoin(url, urlparse(url).path)
pycosio.copyfile(blob_url, os.path.abspath('output.dat'))
```
It fails because an invalid GET against `<azure_storage_endpoint>/name?restype=container&...storage_parameters` is made, resulting in:
```
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:cb7850cd-f01e-00a5-7dae-e9058e000000
Time:2019-04-02T23:48:50.1824812Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>
```

It appears that the `name` part of the request URI (the blob storage container name) is [hardcoded in _base_blob.py](https://github.com/Accelize/pycosio/blob/438ec4c/pycosio/storage/azure_blob/_base_blob.py#L48) and the kwargs passed into that function does not include the blob URI that *is* present in the `_get_instance` call prior in the stack in [storage_manager.py](https://github.com/Accelize/pycosio/blob/438ec4c/pycosio/_core/storage_manager.py#L96). I'm going to investigate more later but if you have pointers let me know :)

**Comment by stewartadam** [comment]
On a tangential note, the code appears to be geared towards file creation (checking if file exists every time a blob class is instantiated) - that assumption can be dangerous for Azure (and I'd imagine other) clouds since SAS tokens may come with 'r' only, or 'w' only access so GET/HEAD verifications fail.

Even once we are detecting the container, it is probably safer to gracefully fail if the SAS token does not permit the validation operations requested and assume the file exists (for reads) or doesn't exist (for writes). Otherwise, documentation should note the requirement for container-level SAS at a minimum.

**Comment by xlz-jgoutin** [comment]
I fixed the hardcoded "name" issue, and successfully run your code snippet with it.

I also fixed the query string not removed from the URL when getting the blob path.

For the file exists check issue. You are true, and I confirm this can also append on other clouds.
For `r` and `w` modes, this only need to not crash if the file can't be accessed with HEAD. The problem is with `a` and `x` modes, in this case, the current Pycosio behavior is to open the file like in `w` mode if it found that the file does not exist (This may result in data loss).
I need to do some tests on this.

**Comment by xlz-jgoutin** [comment]
Fixed some of the "files exists check" issues:
- For ``w`` mode: Now, if no access to the file or if file not exists, use the blob type defined in arguments (or default value) and then open the file with no issue. Previously, it crashed if no permission.
- For ``a`` and ``x`` mode: (Not only for Azure) Different errors are risen by cloud storage for unexisting file and read permission error.  So, it is possible to keep the correct ``a`` and ``x`` behaviour with unexisting files and raising an exception if not enough permission. This should be safe and avoid accidental file overwrite.

I think there is again issues with this, but I not investigated yet:
- Page blobs: Should fail if flushing a partial page, because Pycosio tries to complete the page missing content with content from the page on the server.
- In ``w`` mode, some codes parts need the file size because of the ``a`` mode (That may get from the HEAD request).

**Comment by stewartadam** [comment]
Thanks for the quick turnaround on this!

**Comment by stewartadam** [comment]
Tested the changes and works well for downloads, but I am seeing issues for 'w' mode -- e.g. the same sample above but inverting the copy parameters fails due to insufficient permissions with a 'rw' SAS token to a specific blob:
```
pycosio.copyfile(os.path.abspath('output.dat'), blob_url)
```


```
Traceback (most recent call last):
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/storage/azure.py", line 40, in _handle_azure_exception
    yield
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/storage/azure_blob/_system.py", line 145, in _head
    **client_kwargs)
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 665, in get_container_properties
    return self._perform_request(request, _parse_container, [container_name])
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:81fd7bc2-001e-0008-0257-ea49fb000000
Time:2019-04-03T19:55:06.5759556Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/_core/exceptions.py", line 41, in handle_os_exceptions
    yield
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/_core/functions_core.py", line 81, in decorated
    return cos_function(path, *args, **kwargs)
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/_core/functions_os_path.py", line 124, in isdir
    return system.isdir(system.ensure_dir_path(path))
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/_core/io_base_system.py", line 305, in isdir
    exists = self.exists(path=path, client_kwargs=client_kwargs)
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/_core/io_base_system.py", line 135, in exists
    self.head(path, client_kwargs)
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/_core/io_base_system.py", line 379, in head
    return self._head(client_kwargs)
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/storage/azure_blob/_system.py", line 145, in _head
    **client_kwargs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/user/virtualenvs/pycosio-bFGvO_dA/lib/python3.7/site-packages/pycosio/storage/azure.py", line 44, in _handle_azure_exception
    raise _ERROR_CODES[exception.status_code](str(exception))
pycosio._core.exceptions.ObjectPermissionError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:81fd7bc2-001e-0008-0257-ea49fb000000
Time:2019-04-03T19:55:06.5759556Z</Message></Error>
```

**Comment by stewartadam** [comment]
Took a stab at it, still reading through the code but let me know what you think:
https://github.com/stewartadam/pycosio/commit/311ea76b99a8666510ce457b416edcf4368f0dcc

It adds an `assume_exists` flag so that on mount (Azure or otherwise), we can force the system base I/O class to ignore `ObjectPermissionErrors` and instead simply return `True` if a file list cannot be retrieved.

This should cause operations like `copyfile` to proceed correctly, and the subsequent reads/writes will fail anyways if the signed resource does not have appropriate permissions.

`assume_exists` is a boolean defaulting to current behavior (`False`) but in the case of the Azure base class, if `sas_token` is detected in the storage parameters and assume_exists was not explicitly provided, it will set it to True so that we can avoid requiring an account-level SAS for all operations (since listing a container can only be done via account-level SAS)

**Comment by xlz-jgoutin** [comment]
I like the method, but I see some issues with it:

* Changing ``SystemBase.exits`` behaviour in a general way will break ``pycosio._core.functions_os_path`` ``exists``, ``isdir`` and ``isfile`` functions that should still raise exceptions if file or directory cannot be accessed.
* On Azure, we have the SAS token to know if we need to change set the flag or not. On some other cloud storage, access is managed by policies more globally (For specific users, compute instances, ...), and it may be difficult to set the correct flag value when mounting.
* I prefer to keep the flag in the internal code and keep the public function ``mount`` as simple as possible.

I propose to move the flag directly in ``SystemBase`` methods '(``exits``, ``isdir``, ``isfile``)  and set it only when relevant in the code.

Currently, this should only concern ``copy`` and ``copyfile`` functions that currently call ``functions_os_path.isdir`` (But should use ``get_instance(dst).isdir`` to allow the flag use:
These lines check if parent directory exists, ``assume_exists`` should be ``True``:
https://github.com/Accelize/pycosio/blob/605fd46869c45282647516585cc82f180615bb4d/pycosio/_core/functions_shutil.py#L106
https://github.com/Accelize/pycosio/blob/605fd46869c45282647516585cc82f180615bb4d/pycosio/_core/functions_shutil.py#L140

Therefore, this one should have an assume_exists that return ``False`` on ``PermissionError```:
https://github.com/Accelize/pycosio/blob/605fd46869c45282647516585cc82f180615bb4d/pycosio/_core/functions_shutil.py#L102

To have the excepted behaviour with this last line. We can change the ``assume_exists`` flag behaviour as follow:
* If ``None`` (Default value): re-raise exception.
* If ``True`` or ``False`: return the specified value.

**Comment by xlz-jgoutin** [comment]
Should be fixed in 39cd930.

Added the `assume_exists` flag to the `SystemBase` `exists`, `isdir `and `isfile`.

Fixed `copy` and `copyfile` to trie to copy if no read access to check the target directory. (Fixed with simple try/except instead of `assume_exists` to not break local directory check.

**Comment by stewartadam** [comment]
Thanks for this - I think it tackles the second traceback from above, but the first (from `get_container_properties`) is still happening for me when using a 'rw' or 'w' permission container SAS token:
```INFO:azure.storage.common.storageclient:Client-Request-ID=bd597cdc-66e3-11e9-b2e7-acde48001122 Outgoing request: Method=GET, Path=/outputs, Query={'restype': 'container', 'timeout': None, 'sv': '2018-03-28', 'si': 'rw', 'sr': 'c', 'sig': 'REDACTED'}, Headers={'x-ms-lease-id': None, 'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.4.0-1.4.0 (Python CPython 3.7.3; Darwin 18.5.0)', 'x-ms-client-request-id': 'bd597cdc-66e3-11e9-b2e7-acde48001122', 'x-ms-date': 'Wed, 24 Apr 2019 22:53:13 GMT'}.
INFO:azure.storage.common.storageclient:Client-Request-ID=bd597cdc-66e3-11e9-b2e7-acde48001122 Receiving Response: Server-Timestamp=Wed, 24 Apr 2019 22:53:13 GMT, Server-Request-ID=50b1ac88-b01e-00a4-6ef0-fa5a52000000, HTTP Status Code=403, Message=This request is not authorized to perform this operation., Headers={'content-length': '246', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '50b1ac88-b01e-00a4-6ef0-fa5a52000000', 'x-ms-version': '2018-03-28', 'x-ms-error-code': 'AuthorizationFailure', 'date': 'Wed, 24 Apr 2019 22:53:13 GMT'}.
INFO:azure.storage.common.storageclient:Client-Request-ID=bd597cdc-66e3-11e9-b2e7-acde48001122 Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Wed, 24 Apr 2019 22:53:13 GMT, Server-Request-ID=50b1ac88-b01e-00a4-6ef0-fa5a52000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:50b1ac88-b01e-00a4-6ef0-fa5a52000000Time:2019-04-24T22:53:13.2607525Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=bd597cdc-66e3-11e9-b2e7-acde48001122 Retry policy did not allow for a retry: Server-Timestamp=Wed, 24 Apr 2019 22:53:13 GMT, Server-Request-ID=50b1ac88-b01e-00a4-6ef0-fa5a52000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:50b1ac88-b01e-00a4-6ef0-fa5a52000000Time:2019-04-24T22:53:13.2607525Z</Message></Error>.

...

Traceback (most recent call last):
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/src/pycosio/pycosio/storage/azure.py", line 40, in _handle_azure_exception
    yield
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/src/pycosio/pycosio/storage/azure_blob/_system.py", line 145, in _head
    **client_kwargs)
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 665, in get_container_properties
    return self._perform_request(request, _parse_container, [container_name])
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/Users/stewartadam/devel/virtualenvs/container-filetransfer-aZPvO_gI/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure
```

**Comment by stewartadam** [comment]
Tracing the exceptions, it looks like a `PermissionError` is raised instead of `ObjectPermissionError` here: https://github.com/Accelize/pycosio/commit/39cd93049ea2668497a5bc61253df684dba88e6e#diff-f75850ab2dec8a299d440d9485559407R112

Not sure if we need to catch both, or if just PermissionError is sufficient.

**Comment by xlz-jgoutin** [comment]
Thanks for the report, I'll look at this once back from 2 weeks of holiday.

**Comment by xlz-jgoutin** [comment]
This should be fixed in 61bee51

The error was exactly what you said: ``PermissionError`` needs to be caught because internal exceptions Pycosio are already converted to standard exceptions by ``isdir``.

**Comment by stewartadam** [comment]
Confirmed working, thanks!
